#!/usr/bin/env python3

import numpy as np
from scipy.io.wavfile import write as wavwrite

MAX_INT16 = 2**15 - 1

F = 44100

T = 0.5

N = int(T * F)

t = T * np.arange(0, N) / N

sapo = (np.sin(np.pi * t / T)**4 *
        np.sin(10 * np.pi * t / T) *
        (np.cos(2 * np.pi * 500 * t) + 0.5 * np.cos(2 * np.pi * 1500 * t)))

D = 10
M = int(D * F)

saporsegundo = 0.7

Q = int(D * saporsegundo)

def randomsapo():
    ks = np.random.randint(M, size=(Q, ))
    ruido = np.zeros(M)
    for k in ks:
        L = min(N, M-k)
        ruido[k:(k + L)] += sapo[:L]
    return ruido

saporhectarea = 50
H = int(1 * saporhectarea)
rs = np.random.rand(H, 2) * 2 - 1

fondo = np.zeros(M)

for r in rs:
    d = np.linalg.norm(r)
    fondo += randomsapo() / (d**2)

fondo /= fondo.max()
fondo *= MAX_INT16 / 2
fondo = fondo.astype(np.int16)
wavwrite('/tmp/sapoisson.wav', F, fondo)
