#!/usr/bin/env python3

import numpy as np
from scipy.io.wavfile import write as wavwrite

# TODO: ¡¡¡se puede hacer estereo!!!

MAX_INT16 = 2**15 - 1

F = 44100

T = 0.5

N = int(T * F)

t = T * np.arange(0, N) / N

sapo = (np.sin(np.pi * t / T)**4 *
        np.sin(19 * np.pi * t / T) *
        (np.cos(2 * np.pi * 753 * t) + 0.5 * np.cos(2 * np.pi * 753*2 * t)))

D = 10
M = int(D * F)

saporsegundo = 0.25

Q = int(D * saporsegundo)

def randomsapo():
    ks = np.random.randint(M - N, size=(Q, ))
    ruido = np.zeros(M)
    for k in ks:
        ruido[k:(k + N)] += sapo
    return ruido

saporhectarea = 25
H = int(1 * saporhectarea)
rs = np.random.rand(H, 2) * 2 - 1

fondo = np.zeros(M)

for r in rs:
    d = np.linalg.norm(r)
    fondo += randomsapo() / (0.01 + d)**2

fondo /= fondo.max()
fondo *= MAX_INT16 / 2
fondo = fondo.astype(np.int16)
wavwrite('/tmp/sapoisson.wav', F, fondo)
